PP-7021 Create paas test releases
alphagov/pay-omnibus pull request #339
Opened 2020-09-24 11:44 UTC by danworth

After a pre-release with the tag format `paas_release-n` has been
deployed and the smoke tests have passed, create a pre-release with the tag
`paas_release_test-n` which can then be deployed into staging.

This is just for Adminusers and will apply the same to the other apps if
we agree on this approach.

## WHAT ##
As described above. I've tested this out and the resulting pre-release is here: 
https://github.com/alphagov/pay-adminusers/releases/tag/paas_release_test-62

2020-09-24 14:30 UTC, danworth commented
To anyone reviewing this from beyond Hufflepuff, the `concourse-ci/test` always fail on the pipeline linter, we're yet to clean them up

2020-09-25 09:09 UTC, alexbishop1 requested changes

2020-09-25 09:09 UTC, alexbishop1 commented on ci/pipelines/test-deploy.yml
> +  - &create-release-metatdata
“metatdata”

2020-09-25 09:13 UTC, alexbishop1 approved these changes

2020-09-25 09:13 UTC, danworth commented on ci/pipelines/test-deploy.yml
> +  - &create-release-metatdata
thanks I've fixed it

2020-09-25 09:14 UTC, merged